"""Changelog Traduction.

Watches every `update.*` entity. When one becomes available, fetches its
release notes (GitHub release, Supervisor add-on changelog, or the Home
Assistant release-notes page, depending on the source) and asks a Home
Assistant AI Task entity to translate/summarize them into the target
language - by default the language Home Assistant's own interface is set
to (`hass.config.language`), overridable per install. Delivers the result
as a persistent notification and/or a mobile notification.

Read-only: this integration never calls any control/write service other than
notification and persistent_notification. It does not install updates, does
not touch your configuration, and does not control any device.
"""
from __future__ import annotations

import logging
import re
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import (
    CoreState,
    Event,
    HomeAssistant,
    EVENT_HOMEASSISTANT_STARTED,
    EVENT_STATE_CHANGED,
)
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.storage import Store

from .const import DOMAIN, STORAGE_KEY, STORAGE_VERSION

_LOGGER = logging.getLogger(__name__)

# Matches https://github.com/<owner>/<repo>/releases/tag/<tag>
# or the shorter .../releases/<tag> form some integrations expose.
GITHUB_RELEASE_RE = re.compile(
    r"github\.com/(?P<owner>[^/]+)/(?P<repo>[^/]+)/releases/(?:tag/)?(?P<tag>[^/?#]+)"
)

# Supervisor add-on update entities expose no release_url at all, but their
# entity_picture always follows this pattern (see homeassistant/components/
# hassio/update.py: `f"/api/hassio/addons/{self._addon_slug}/icon"`), which
# lets us recover the add-on slug to fetch its changelog a different way.
ADDON_SLUG_RE = re.compile(r"/api/hassio/addons/(?P<slug>[^/]+)/icon")

# Home Assistant Core's own release_url (stable/beta channel) is a *page*,
# not a versioned API resource: https://www.home-assistant.io/latest-release-notes/
# (or the rc. subdomain for beta). It's not per-version machine-readable
# like a GitHub release, so instead of parsing it, we fetch the raw page
# and let the AI task do extraction + translation together.
HA_RELEASE_NOTES_RE = re.compile(r"home-assistant\.io/(?:latest-release-notes|blog)/")

MAX_CHANGELOG_CHARS = 4000
# The release-notes HTML page carries a lot of nav/footer noise around the
# actual content, so give it a larger budget than the clean GitHub/Supervisor
# text sources get.
MAX_HTML_CHANGELOG_CHARS = 12000

# Friendly names for the AI prompt - purely cosmetic (an LLM understands
# "the language with ISO 639-1 code 'xx'" fine on its own), but naming the
# language explicitly when we know it reads more naturally and avoids any
# ambiguity for codes that map to more than one common language name.
LANGUAGE_NAMES: dict[str, str] = {
    "fr": "French (Français)",
    "en": "English",
    "de": "German (Deutsch)",
    "es": "Spanish (Español)",
    "it": "Italian (Italiano)",
    "pt": "Portuguese (Português)",
    "nl": "Dutch (Nederlands)",
    "pl": "Polish (Polski)",
    "sv": "Swedish (Svenska)",
    "no": "Norwegian (Norsk)",
    "da": "Danish (Dansk)",
    "fi": "Finnish (Suomi)",
    "ru": "Russian (Русский)",
    "uk": "Ukrainian (Українська)",
    "cs": "Czech (Čeština)",
    "sk": "Slovak (Slovenčina)",
    "ro": "Romanian (Română)",
    "hu": "Hungarian (Magyar)",
    "el": "Greek (Ελληνικά)",
    "tr": "Turkish (Türkçe)",
    "ja": "Japanese (日本語)",
    "zh": "Chinese (中文)",
    "ko": "Korean (한국어)",
}

# Best-effort localized copy for the parts of a message that are NOT
# generated by the AI (used when translation itself fails, or when there is
# no changelog source to translate at all). Only a handful of languages are
# hand-written; everything else falls back to English rather than silently
# mixing languages.
FALLBACK_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "notif_title": "Update: {title}",
        "no_changelog": "Update available for {title}{version} - release notes unavailable for this source.",
        "translation_failed": "{title}: update available (automatic translation failed).",
    },
    "fr": {
        "notif_title": "Mise à jour : {title}",
        "no_changelog": "Mise à jour disponible pour {title}{version} — notes de version non disponibles pour cette source.",
        "translation_failed": "{title} : mise à jour disponible (échec de la traduction automatique).",
    },
    "de": {
        "notif_title": "Update: {title}",
        "no_changelog": "Update verfügbar für {title}{version} - Versionshinweise für diese Quelle nicht verfügbar.",
        "translation_failed": "{title}: Update verfügbar (automatische Übersetzung fehlgeschlagen).",
    },
    "es": {
        "notif_title": "Actualización: {title}",
        "no_changelog": "Actualización disponible para {title}{version}: notas de la versión no disponibles para esta fuente.",
        "translation_failed": "{title}: actualización disponible (fallo la traducción automática).",
    },
}


def _fallback(lang: str, key: str, **kwargs: Any) -> str:
    strings = FALLBACK_STRINGS.get(lang, FALLBACK_STRINGS["en"])
    return strings[key].format(**kwargs)


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up Changelog Traduction from a config entry."""
    store: Store = Store(hass, STORAGE_VERSION, STORAGE_KEY)
    notified: dict[str, str] = await store.async_load() or {}
    options: dict[str, Any] = dict(entry.data)
    lang = options.get("language") or hass.config.language or "en"

    async def _process_state(entity_id: str, new_state: Any) -> None:
        """Process one update entity that is currently (or just became) 'on'."""
        latest_version = new_state.attributes.get("latest_version")
        release_url = new_state.attributes.get("release_url") or ""
        entity_picture = new_state.attributes.get("entity_picture") or ""
        title = new_state.attributes.get("title") or new_state.name or entity_id

        _LOGGER.debug(
            "Processing %s: latest_version=%s release_url=%r already_notified=%s lang=%s",
            entity_id, latest_version, release_url, notified.get(entity_id), lang,
        )

        if latest_version and notified.get(entity_id) == latest_version:
            _LOGGER.debug("Skipping %s: already notified for %s", entity_id, latest_version)
            return  # Already announced this exact version (survives restarts).

        match = GITHUB_RELEASE_RE.search(release_url)
        changelog_text: str | None = None
        noisy_source = False
        if match:
            changelog_text = await _fetch_github_release_body(hass, match)

        if not changelog_text:
            # No usable GitHub release_url (this is the normal case for
            # Supervisor add-ons, which never set release_url at all) - try
            # recovering the add-on slug from entity_picture and fetching
            # its changelog straight from Supervisor instead.
            addon_match = ADDON_SLUG_RE.search(entity_picture)
            if addon_match:
                changelog_text = await _fetch_addon_changelog(
                    hass, addon_match.group("slug")
                )

        if not changelog_text and HA_RELEASE_NOTES_RE.search(release_url):
            # Home Assistant Core/Supervisor/OS "latest release notes" page -
            # noisy HTML, no clean per-version API. Fetched raw and handed
            # to the AI task, which extracts the real content itself.
            changelog_text = await _fetch_html_page_text(hass, release_url)
            noisy_source = bool(changelog_text)

        _LOGGER.debug(
            "%s: github_match=%s changelog_text_len=%s noisy_source=%s",
            entity_id, bool(match), len(changelog_text) if changelog_text else 0, noisy_source,
        )

        if changelog_text:
            message = await _translate_changelog(
                hass, options, title, changelog_text, lang, noisy_source=noisy_source
            )
        else:
            message = _fallback(
                lang, "no_changelog", title=title,
                version=f" ({latest_version})" if latest_version else "",
            )
        _LOGGER.debug("%s: final message=%r", entity_id, message)

        delivered = await _deliver(hass, options, title, message, lang)
        _LOGGER.debug("%s: delivered=%s", entity_id, delivered)

        # Only mark as notified if delivery actually succeeded on at least
        # one channel - a failed delivery (e.g. notify service not yet
        # registered this early in boot) must be retried, not silently
        # swallowed.
        if latest_version and delivered:
            notified[entity_id] = latest_version
            await store.async_save(notified)

    async def _handle_state_changed(event: Event) -> None:
        entity_id = event.data.get("entity_id")
        if not entity_id or not entity_id.startswith("update."):
            return

        new_state = event.data.get("new_state")
        old_state = event.data.get("old_state")
        if new_state is None or new_state.state != "on":
            return
        if old_state is not None and old_state.state == "on":
            # Already "on" before this event (e.g. an unrelated attribute
            # update on the same entity) - not a fresh availability.
            return

        await _process_state(entity_id, new_state)

    remove_listener = hass.bus.async_listen(EVENT_STATE_CHANGED, _handle_state_changed)
    hass.data.setdefault(DOMAIN, {})[entry.entry_id] = remove_listener

    async def _startup_catch_up(_event: Event | None = None) -> None:
        # Entities that were ALREADY pending before this integration was
        # installed/reloaded never fire an "off -> on" state event for us
        # to observe, so scan the current snapshot once HA has FULLY
        # started - not during async_setup_entry itself, which can run
        # before other integrations (e.g. mobile_app's notify service,
        # or the very update.* entities we're scanning for) have finished
        # registering.
        pending = [s for s in hass.states.async_all("update") if s.state == "on"]
        _LOGGER.debug("Changelog Traduction startup catch-up: %d pending update(s)", len(pending))
        for state in pending:
            await _process_state(state.entity_id, state)

    # IMPORTANT: hass.is_running is True for BOTH CoreState.starting AND
    # CoreState.running - it does NOT mean "startup fully finished". Using
    # it here would run the catch-up scan during the "starting" phase,
    # before other integrations' entities/services exist yet, silently
    # finding nothing (or racing notify). Only CoreState.running (reached
    # right when EVENT_HOMEASSISTANT_STARTED fires) means startup is truly
    # complete, so we gate on that explicitly.
    if hass.state is CoreState.running:
        # HA already fully started (e.g. this is a config entry reload,
        # not a fresh boot) - safe to scan right away.
        await _startup_catch_up()
    else:
        hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STARTED, _startup_catch_up)

    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload the config entry and stop listening."""
    remove_listener = hass.data.get(DOMAIN, {}).pop(entry.entry_id, None)
    if remove_listener:
        remove_listener()
    return True


async def async_remove_entry(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Called when the config entry is fully removed (not on unload/reload).

    Deletes the "already notified" storage file so that a future reinstall
    starts clean instead of silently inheriting stale version bookkeeping
    from a previous install, and so nothing lingers in .storage/ once the
    integration itself has been removed.
    """
    store: Store = Store(hass, STORAGE_VERSION, STORAGE_KEY)
    await store.async_remove()


async def _fetch_github_release_body(hass: HomeAssistant, match: re.Match) -> str | None:
    """Fetch a GitHub release's body text via the public REST API."""
    owner, repo, tag = match.group("owner"), match.group("repo"), match.group("tag")
    session = async_get_clientsession(hass)
    url = f"https://api.github.com/repos/{owner}/{repo}/releases/tags/{tag}"
    try:
        async with session.get(
            url,
            timeout=15,
            headers={"Accept": "application/vnd.github+json"},
        ) as resp:
            if resp.status != 200:
                _LOGGER.debug("GitHub release fetch failed (%s) for %s", resp.status, url)
                return None
            data = await resp.json()
    except Exception as err:  # noqa: BLE001 - network errors of any kind are non-fatal here
        _LOGGER.debug("GitHub release fetch error for %s: %s", url, err)
        return None
    body = data.get("body")
    return body.strip() if body else None


async def _fetch_addon_changelog(hass: HomeAssistant, slug: str) -> str | None:
    """Fetch a Supervisor add-on's changelog text.

    Add-on update entities have no release_url and are not GitHub-hosted
    releases - their changelog instead comes from Supervisor itself, at the
    same "/addons/{slug}/changelog" endpoint the HA frontend calls. There is
    no public/stable API for this from a custom integration, so this reuses
    Home Assistant's own internal Supervisor connection (the `hassio`
    integration's handler). This reaches into `hassio` internals that are
    not a documented custom-integration API and could break on a future HA
    update - if that happens, this simply returns None and the caller falls
    back to the generic "update available" message, exactly as if no
    changelog had been found at all.
    """
    try:
        from homeassistant.components.hassio.const import (  # noqa: PLC0415
            DATA_COMPONENT,
        )

        supervisor = hass.data[DATA_COMPONENT]
        changelog = await supervisor.send_command(
            f"/addons/{slug}/changelog", method="get", return_text=True
        )
    except Exception as err:  # noqa: BLE001 - any failure here is non-fatal
        _LOGGER.debug("Add-on changelog fetch failed for %s: %s", slug, err)
        return None
    return changelog.strip() if changelog else None


TAG_RE = re.compile(r"<script[^>]*>.*?</script>|<style[^>]*>.*?</style>|<[^>]+>", re.DOTALL)
WHITESPACE_RE = re.compile(r"[ \t]+")
BLANK_LINES_RE = re.compile(r"\n{3,}")


async def _fetch_html_page_text(hass: HomeAssistant, url: str) -> str | None:
    """Fetch a web page and strip it down to plain-ish text.

    Crude tag-stripping only (no real HTML parser is bundled) - this leaves
    some navigation/footer text mixed in with the real content, which is why
    the translation prompt is told to ignore anything that isn't actual
    release notes rather than assuming the input is already clean.
    """
    session = async_get_clientsession(hass)
    try:
        async with session.get(url, timeout=15) as resp:
            if resp.status != 200:
                _LOGGER.debug("Release notes page fetch failed (%s) for %s", resp.status, url)
                return None
            html = await resp.text()
    except Exception as err:  # noqa: BLE001
        _LOGGER.debug("Release notes page fetch error for %s: %s", url, err)
        return None

    text = TAG_RE.sub("\n", html)
    text = WHITESPACE_RE.sub(" ", text)
    text = BLANK_LINES_RE.sub("\n\n", text)
    text = text.strip()
    return text or None


async def _translate_changelog(
    hass: HomeAssistant,
    options: dict[str, Any],
    title: str,
    changelog_text: str,
    lang: str,
    *,
    noisy_source: bool = False,
) -> str:
    """Ask the configured AI Task entity to translate/summarize the changelog.

    Target language defaults to Home Assistant's own interface language
    (`hass.config.language`) unless overridden in the config entry.

    noisy_source=True is used for text scraped from an HTML page (rather
    than a clean GitHub/Supervisor API body) - it both allows a larger input
    budget (the real content can sit well past the nav/footer boilerplate)
    and tells the model explicitly to ignore anything that isn't actual
    release notes.
    """
    ai_task_entity = options.get("ai_task_entity")
    max_chars = MAX_HTML_CHANGELOG_CHARS if noisy_source else MAX_CHANGELOG_CHARS
    language_label = LANGUAGE_NAMES.get(lang, f"ISO 639-1 code '{lang}'")
    noise_hint = (
        " The provided text was scraped from a raw web page and likely contains "
        "navigation menus, footer text, or other unrelated content: ignore anything "
        "that isn't actually the release notes for this version."
        if noisy_source
        else ""
    )
    instructions = (
        f"Translate and summarize, in {language_label}, in 3 to 5 sentences "
        f"maximum, the following release notes for the Home Assistant "
        f"integration '{title}'. Keep only the changes that matter to an "
        "end user, ignore purely internal technical details (refactoring, "
        "CI, code typos)." + noise_hint + " Reply only with the translated "
        "text, with no introduction or meta-commentary.\n\n"
        f"{changelog_text[:max_chars]}"
    )
    try:
        result = await hass.services.async_call(
            "ai_task",
            "generate_data",
            {
                "task_name": "changelog translation",
                "instructions": instructions,
                "entity_id": ai_task_entity,
            },
            blocking=True,
            return_response=True,
        )
        text = result.get("data") if isinstance(result, dict) else None
        return str(text).strip() if text else _fallback(lang, "no_changelog", title=title, version="")
    except Exception as err:  # noqa: BLE001
        _LOGGER.warning("AI Task translation failed for %s: %s", title, err)
        return _fallback(lang, "translation_failed", title=title)


async def _deliver(
    hass: HomeAssistant, options: dict[str, Any], title: str, message: str, lang: str
) -> bool:
    """Deliver the translated summary via the configured notification channels.

    Returns True if at least one enabled channel succeeded, False otherwise
    (or if no channel was enabled at all).
    """
    delivered = False
    notif_title = _fallback(lang, "notif_title", title=title)

    if options.get("use_persistent_notification", True):
        try:
            await hass.services.async_call(
                "persistent_notification",
                "create",
                {
                    "title": notif_title,
                    "message": message,
                    "notification_id": f"{DOMAIN}_{title}",
                },
            )
            delivered = True
            _LOGGER.debug("persistent_notification.create succeeded for %s", title)
        except Exception as err:  # noqa: BLE001
            _LOGGER.warning("persistent_notification.create failed: %s", err)

    if options.get("use_mobile_notification", True):
        notify_target = options.get("notify_service")
        # The config flow's entity selector has multiple=True, so this is
        # normally a list (one or more notify.* entities, e.g. phone + tablet)
        # - but tolerate a bare string too (single entity picked, or an
        # older entry from before multi-device support was added).
        if isinstance(notify_target, str):
            notify_target = [notify_target]
        if not notify_target:
            _LOGGER.warning(
                "use_mobile_notification is on but no notify_service is configured "
                "for %s - skipping mobile notification.", title,
            )
        else:
            # notify_target entries are notify.* ENTITY ids picked via the
            # config flow's entity selector (e.g. "notify.iphone_fred") -
            # modern HA notify entities are not callable as their own
            # dynamic service (there is no such thing as a
            # "notify.iphone_fred" service). They must be addressed
            # through the generic notify.send_message service with an
            # explicit target - passing all of them at once sends to every
            # configured device in a single call.
            try:
                await hass.services.async_call(
                    "notify",
                    "send_message",
                    {"title": notif_title, "message": message},
                    target={"entity_id": notify_target},
                )
                delivered = True
                _LOGGER.debug("Notification via %s succeeded for %s", notify_target, title)
            except Exception as err:  # noqa: BLE001
                _LOGGER.warning("Notification via %s failed: %s", notify_target, err)

    return delivered
