"""Changelog Traduction.

Watches every `update.*` entity. When one becomes available, fetches its
release notes (GitHub release, Supervisor add-on changelog, or the Home
Assistant release-notes page, depending on the source) and asks a Home
Assistant AI Task entity to translate/summarize them into the target
language - by default the language Home Assistant's own interface is set
to (`hass.config.language`), overridable per install. Delivers the result
as a persistent notification and/or a mobile notification.

Read-only: this integration never calls any control/write service other than
notification and persistent_notification. It does not install updates, does
not touch your configuration, and does not control any device.
"""
from __future__ import annotations

import asyncio
import logging
import re
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import (
    CoreState,
    Event,
    HomeAssistant,
    EVENT_HOMEASSISTANT_STARTED,
    EVENT_STATE_CHANGED,
)
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.storage import Store

from .const import DOMAIN, STORAGE_KEY, STORAGE_VERSION

_LOGGER = logging.getLogger(__name__)

# Sentinel returned by _translate_changelog() when the AI Task call itself
# failed/errored during alert-mode breaking-change classification. Distinct
# from a legitimate None (no changelog text at all, or the AI confirmed the
# release is "not breaking") so the caller can skip notifying WITHOUT
# marking the version as seen - an unknown classification must be retried
# later, not silently treated as settled.
_AI_CLASSIFICATION_UNKNOWN = object()

# Matches https://github.com/<owner>/<repo>/releases/tag/<tag>
# or the shorter .../releases/<tag> form some integrations expose.
GITHUB_RELEASE_RE = re.compile(
    r"github\.com/(?P<owner>[^/]+)/(?P<repo>[^/]+)/releases/(?:tag/)?(?P<tag>[^/?#]+)"
)

# Supervisor add-on update entities expose no release_url at all, but their
# entity_picture always follows this pattern (see homeassistant/components/
# hassio/update.py: `f"/api/hassio/addons/{self._addon_slug}/icon"`), which
# lets us recover the add-on slug to fetch its changelog a different way.
ADDON_SLUG_RE = re.compile(r"/api/hassio/addons/(?P<slug>[^/]+)/icon")

# Home Assistant Core's own release_url (stable/beta channel) is a *page*,
# not a versioned API resource: https://www.home-assistant.io/latest-release-notes/
# (or the rc. subdomain for beta). It's not per-version machine-readable
# like a GitHub release, so instead of parsing it, we fetch the raw page
# and let the AI task do extraction + translation together.
HA_RELEASE_NOTES_RE = re.compile(r"home-assistant\.io/(?:latest-release-notes|blog)/")

MAX_CHANGELOG_CHARS = 4000
# The release-notes HTML page carries a lot of nav/footer noise around the
# actual content, so give it a larger budget than the clean GitHub/Supervisor
# text sources get.
MAX_HTML_CHANGELOG_CHARS = 12000

# Friendly names for the AI prompt - purely cosmetic (an LLM understands
# "the language with ISO 639-1 code 'xx'" fine on its own), but naming the
# language explicitly when we know it reads more naturally and avoids any
# ambiguity for codes that map to more than one common language name.
LANGUAGE_NAMES: dict[str, str] = {
    "fr": "French (Français)",
    "en": "English",
    "de": "German (Deutsch)",
    "es": "Spanish (Español)",
    "it": "Italian (Italiano)",
    "pt": "Portuguese (Português)",
    "nl": "Dutch (Nederlands)",
    "pl": "Polish (Polski)",
    "sv": "Swedish (Svenska)",
    "no": "Norwegian (Norsk)",
    "da": "Danish (Dansk)",
    "fi": "Finnish (Suomi)",
    "ru": "Russian (Русский)",
    "uk": "Ukrainian (Українська)",
    "cs": "Czech (Čeština)",
    "sk": "Slovak (Slovenčina)",
    "ro": "Romanian (Română)",
    "hu": "Hungarian (Magyar)",
    "el": "Greek (Ελληνικά)",
    "tr": "Turkish (Türkçe)",
    "ja": "Japanese (日本語)",
    "zh": "Chinese (中文)",
    "ko": "Korean (한국어)",
}

# Best-effort localized copy for the parts of a message that are NOT
# generated by the AI (used when translation itself fails, or when there is
# no changelog source to translate at all). Only a handful of languages are
# hand-written; everything else falls back to English rather than silently
# mixing languages.
FALLBACK_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "notif_title": "Update: {title}",
        "no_changelog": "Update available for {title}{version} - release notes unavailable for this source.",
        "translation_failed": "{title}: update available (automatic translation failed).",
    },
    "fr": {
        "notif_title": "Mise à jour : {title}",
        "no_changelog": "Mise à jour disponible pour {title}{version} — notes de version non disponibles pour cette source.",
        "translation_failed": "{title} : mise à jour disponible (échec de la traduction automatique).",
    },
    "de": {
        "notif_title": "Update: {title}",
        "no_changelog": "Update verfügbar für {title}{version} - Versionshinweise für diese Quelle nicht verfügbar.",
        "translation_failed": "{title}: Update verfügbar (automatische Übersetzung fehlgeschlagen).",
    },
    "es": {
        "notif_title": "Actualización: {title}",
        "no_changelog": "Actualización disponible para {title}{version}: notas de la versión no disponibles para esta fuente.",
        "translation_failed": "{title}: actualización disponible (fallo la traducción automática).",
    },
}


def _fallback(lang: str, key: str, **kwargs: Any) -> str:
    strings = FALLBACK_STRINGS.get(lang, FALLBACK_STRINGS["en"])
    return strings[key].format(**kwargs)


# Section headers for the categorized notification body (see
# _format_categorized_message below). These are fixed, hand-written
# strings - NOT AI-generated - so the layout stays consistent regardless
# of what the model returns; only the bullet content itself is
# AI-translated. Only a handful of languages are hand-written, matching
# FALLBACK_STRINGS above; everything else falls back to English.
CATEGORY_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "new_features": "🆕 New",
        "fixes": "🔧 Fixed",
        "breaking_changes": "⚠️ Breaking changes",
        "none": "None",
    },
    "fr": {
        "new_features": "🆕 Nouveautés",
        "fixes": "🔧 Corrections",
        "breaking_changes": "⚠️ Breaking changes",
        "none": "Aucune",
    },
    "de": {
        "new_features": "🆕 Neu",
        "fixes": "🔧 Behoben",
        "breaking_changes": "⚠️ Breaking Changes",
        "none": "Keine",
    },
    "es": {
        "new_features": "🆕 Novedades",
        "fixes": "🔧 Correcciones",
        "breaking_changes": "⚠️ Cambios importantes",
        "none": "Ninguna",
    },
}


def _format_categorized_message(
    lang: str,
    new_features: list[str],
    fixes: list[str],
    breaking_changes: list[str],
    *,
    version_line: str | None = None,
) -> str:
    """Render the three AI-categorized bullet lists into a notification body.

    All three section headers are always shown, even when a category is
    empty (using a localized "none" placeholder) - a reader expects to
    see all three sections and judge for themselves that nothing changed
    in one of them, rather than wonder whether a missing section means
    "empty" or "not checked".
    """
    labels = CATEGORY_LABELS.get(lang, CATEGORY_LABELS["en"])
    sections = [version_line] if version_line else []
    for key, items in (
        ("new_features", new_features),
        ("fixes", fixes),
        ("breaking_changes", breaking_changes),
    ):
        header = labels[key]
        body = "\n".join(f"• {item}" for item in items) if items else f"• {labels['none']}"
        sections.append(f"{header}\n{body}")
    return "\n\n".join(sections)


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up Changelog Traduction from a config entry."""
    store: Store = Store(hass, STORAGE_VERSION, STORAGE_KEY)
    notified: dict[str, str] = await store.async_load() or {}
    # Guards _process_state against processing the same entity+version
    # twice concurrently (see _process_state's wrapper below).
    in_flight: set[str] = set()
    # entry.options overrides entry.data field-by-field once the options
    # flow has been submitted at least once; before that, entry.data (the
    # original setup values) is all there is. Reloading the entry (see the
    # update listener registered below) re-runs this function from scratch,
    # so a settings change always takes effect immediately, no restart
    # needed.
    options: dict[str, Any] = {**entry.data, **entry.options}
    lang = options.get("language") or hass.config.language or "en"

    async def _process_state(entity_id: str, new_state: Any) -> None:
        """Guard _process_state_inner against concurrent double-processing.

        Two state_changed events for the same entity can arrive in quick
        succession (e.g. an unrelated attribute update racing a genuine
        version bump) - both would otherwise see the same not-yet-saved
        'notified' value and could both call the AI Task and send a
        notification for the exact same version. A simple in-flight set
        keyed on entity_id + version closes that window.
        """
        latest_version = new_state.attributes.get("latest_version")
        in_flight_key = f"{entity_id}:{latest_version}"
        if latest_version and in_flight_key in in_flight:
            _LOGGER.debug(
                "Skipping %s: already being processed for %s", entity_id, latest_version
            )
            return
        if latest_version:
            in_flight.add(in_flight_key)
        try:
            await _process_state_inner(entity_id, new_state)
        finally:
            in_flight.discard(in_flight_key)

    async def _process_state_inner(entity_id: str, new_state: Any) -> None:
        """Process one update entity that is currently (or just became) 'on'."""
        excluded_entities = options.get("excluded_entities") or []
        if entity_id in excluded_entities:
            # User explicitly asked to never be notified about this entity
            # (e.g. Spook Blueprint update trackers with no real release
            # notes) - skip before doing any network/AI work at all, and
            # don't record it as "notified" either, so re-including it
            # later picks the version back up normally.
            _LOGGER.debug("Skipping %s: excluded by user configuration", entity_id)
            return

        latest_version = new_state.attributes.get("latest_version")
        release_url = new_state.attributes.get("release_url") or ""
        entity_picture = new_state.attributes.get("entity_picture") or ""
        title = new_state.attributes.get("title") or new_state.name or entity_id
        # Captured once and reused below (both for the "already notified"
        # check and, later, to render a "vOLD -> vNEW" line in the
        # notification body) - notified[entity_id] is not mutated again
        # until delivery succeeds, so this stays valid for the whole call.
        old_version = notified.get(entity_id)

        _LOGGER.debug(
            "Processing %s: latest_version=%s release_url=%r already_notified=%s lang=%s",
            entity_id, latest_version, release_url, old_version, lang,
        )

        if latest_version and old_version == latest_version:
            _LOGGER.debug("Skipping %s: already notified for %s", entity_id, latest_version)
            return  # Already announced this exact version (survives restarts).

        match = GITHUB_RELEASE_RE.search(release_url)
        changelog_text: str | None = None
        noisy_source = False
        if match:
            changelog_text = await _fetch_github_release_body(hass, match)

        addon_match = None
        if not changelog_text:
            # No usable GitHub release_url (this is the normal case for
            # Supervisor add-ons, which never set release_url at all) - try
            # recovering the add-on slug from entity_picture and fetching
            # its changelog straight from Supervisor instead.
            addon_match = ADDON_SLUG_RE.search(entity_picture)
            if addon_match:
                changelog_text = await _fetch_addon_changelog(
                    hass, addon_match.group("slug")
                )

        ha_release_match = None
        if not changelog_text:
            ha_release_match = HA_RELEASE_NOTES_RE.search(release_url)
            if ha_release_match:
                # Home Assistant Core/Supervisor/OS "latest release notes" page -
                # noisy HTML, no clean per-version API. Fetched raw and handed
                # to the AI task, which extracts the real content itself.
                changelog_text = await _fetch_html_page_text(hass, release_url)
                noisy_source = bool(changelog_text)

        # Whether a source was identified at all (GitHub release URL
        # matched, add-on slug recovered, or an HA release-notes URL
        # matched) - independent of whether the actual fetch succeeded.
        # Lets alert mode distinguish "confirmed nothing to classify" from
        # "a fetch failed transiently and should be retried" (see below).
        source_identified = bool(match) or bool(addon_match) or bool(ha_release_match)

        _LOGGER.debug(
            "%s: github_match=%s changelog_text_len=%s noisy_source=%s",
            entity_id, bool(match), len(changelog_text) if changelog_text else 0, noisy_source,
        )

        if changelog_text:
            version_line = None
            if latest_version:
                version_line = (
                    f"{old_version} → {latest_version}"
                    if old_version and old_version != latest_version
                    else latest_version
                )
            message = await _translate_changelog(
                hass, options, title, changelog_text, lang,
                noisy_source=noisy_source, version_line=version_line,
            )
        elif options.get("alert_mode_only"):
            if source_identified:
                # A source was identified (GitHub release, add-on
                # changelog, or the HA release-notes page) but fetching it
                # failed (network error, rate limit, 404...) - unlike "no
                # source at all", this is NOT a confirmed "nothing to
                # classify". Skip WITHOUT marking the version as seen, so
                # it is retried on the next state change or HA restart
                # instead of being silently and permanently skipped just
                # because of a transient failure.
                _LOGGER.debug(
                    "%s: source identified but fetch failed - skipping "
                    "without marking as seen, will retry", entity_id,
                )
                return
            # Genuinely no source at all - nothing to classify as breaking
            # or not, so treat it the same as "not breaking": skip the
            # notification instead of sending a content-free "update
            # available, no notes" message every time (e.g. Blueprint
            # update entities tracked only by raw file hash, which have no
            # real release notes).
            message = None
        else:
            message = _fallback(
                lang, "no_changelog", title=title,
                version=f" ({latest_version})" if latest_version else "",
            )
        _LOGGER.debug("%s: final message=%r", entity_id, message)

        if message is _AI_CLASSIFICATION_UNKNOWN:
            # AI Task classification failed - do NOT mark this version as
            # notified, so it gets re-evaluated on the next state change or
            # HA restart instead of being permanently skipped.
            return

        if message is None:
            # Alert mode determined this release has no breaking changes:
            # nothing to notify, but still record the version as seen so
            # we don't re-run the AI classification on it every refresh
            # cycle.
            if latest_version:
                notified[entity_id] = latest_version
                await store.async_save(notified)
            return

        delivered = await _deliver(hass, options, entity_id, title, message, lang)
        _LOGGER.debug("%s: delivered=%s", entity_id, delivered)

        # Only mark as notified if delivery actually succeeded on at least
        # one channel - a failed delivery (e.g. notify service not yet
        # registered this early in boot) must be retried, not silently
        # swallowed.
        if latest_version and delivered:
            notified[entity_id] = latest_version
            await store.async_save(notified)

    async def _handle_state_changed(event: Event) -> None:
        entity_id = event.data.get("entity_id")
        if not entity_id or not entity_id.startswith("update."):
            return

        new_state = event.data.get("new_state")
        old_state = event.data.get("old_state")
        if new_state is None or new_state.state != "on":
            return
        if old_state is not None and old_state.state == "on":
            # Already "on" before this event. This is usually just an
            # unrelated attribute update on the same entity, but it can
            # also be a genuinely new version becoming available while an
            # update was already pending (latest_version bumped without
            # the state itself flipping off/on) - only skip when the
            # available version attribute is actually unchanged too.
            old_version = old_state.attributes.get("latest_version")
            new_version = new_state.attributes.get("latest_version")
            if old_version == new_version:
                return

        await _process_state(entity_id, new_state)

    remove_listener = hass.bus.async_listen(EVENT_STATE_CHANGED, _handle_state_changed)
    hass.data.setdefault(DOMAIN, {})[entry.entry_id] = remove_listener

    async def _startup_catch_up(_event: Event | None = None) -> None:
        # Entities that were ALREADY pending before this integration was
        # installed/reloaded never fire an "off -> on" state event for us
        # to observe, so scan the current snapshot once HA has FULLY
        # started - not during async_setup_entry itself, which can run
        # before other integrations (e.g. mobile_app's notify service,
        # or the very update.* entities we're scanning for) have finished
        # registering.
        pending = [s for s in hass.states.async_all("update") if s.state == "on"]
        _LOGGER.debug("Changelog Traduction startup catch-up: %d pending update(s)", len(pending))
        # Bounded concurrency instead of one-at-a-time: with many pending
        # updates (e.g. right after a fresh install with dozens of HACS
        # integrations), fully sequential processing means each one waits
        # for the previous one's full GitHub/Supervisor fetch + AI Task
        # round-trip before even starting. A small semaphore lets several
        # run at once without hammering the AI provider or GitHub's rate
        # limit all at once.
        semaphore = asyncio.Semaphore(3)

        async def _bounded(state: Any) -> None:
            async with semaphore:
                await _process_state(state.entity_id, state)

        await asyncio.gather(*(_bounded(state) for state in pending))

    # IMPORTANT: hass.is_running is True for BOTH CoreState.starting AND
    # CoreState.running - it does NOT mean "startup fully finished". Using
    # it here would run the catch-up scan during the "starting" phase,
    # before other integrations' entities/services exist yet, silently
    # finding nothing (or racing notify). Only CoreState.running (reached
    # right when EVENT_HOMEASSISTANT_STARTED fires) means startup is truly
    # complete, so we gate on that explicitly.
    if hass.state is CoreState.running:
        # HA already fully started (e.g. this is a config entry reload,
        # not a fresh boot) - safe to scan right away.
        await _startup_catch_up()
    else:
        hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STARTED, _startup_catch_up)

    # Reload the entry whenever its options change, so a setting picked in
    # the new options flow (notification targets, AI Task entity, language,
    # alert mode...) takes effect immediately instead of requiring a manual
    # reload or a full restart.
    entry.async_on_unload(entry.add_update_listener(_async_update_listener))

    return True


async def _async_update_listener(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Reload the config entry when its options are changed."""
    await hass.config_entries.async_reload(entry.entry_id)


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload the config entry and stop listening."""
    remove_listener = hass.data.get(DOMAIN, {}).pop(entry.entry_id, None)
    if remove_listener:
        remove_listener()
    return True


async def _fetch_github_release_body(hass: HomeAssistant, match: re.Match) -> str | None:
    """Fetch a GitHub release's body text via the public REST API.

    Retries once after a short delay on transport-level failures (timeout,
    connection error) - a transient network hiccup shouldn't permanently
    fall back to the generic "update available" message for an entire
    version. HTTP-level errors (404, 403 rate limit...) are NOT retried,
    since those are not transient.
    """
    owner, repo, tag = match.group("owner"), match.group("repo"), match.group("tag")
    session = async_get_clientsession(hass)
    url = f"https://api.github.com/repos/{owner}/{repo}/releases/tags/{tag}"
    for attempt in range(2):
        try:
            async with session.get(
                url,
                timeout=15,
                headers={"Accept": "application/vnd.github+json"},
            ) as resp:
                remaining = resp.headers.get("X-RateLimit-Remaining")
                if remaining is not None and remaining.isdigit() and int(remaining) <= 1:
                    # The unauthenticated GitHub API is capped at 60
                    # requests/hour (documented in README "Known
                    # limitations"). Log this loudly (WARNING, not DEBUG)
                    # so it's actually visible instead of silently causing
                    # every subsequent update this hour to fall back to
                    # the generic "update available" message.
                    _LOGGER.warning(
                        "GitHub API rate limit nearly exhausted (%s "
                        "remaining, resets at unix time %s) - further "
                        "changelog fetches this hour will likely fall "
                        "back to the generic 'update available' message",
                        remaining, resp.headers.get("X-RateLimit-Reset"),
                    )
                if resp.status != 200:
                    _LOGGER.debug(
                        "GitHub release fetch failed (%s) for %s", resp.status, url
                    )
                    return None
                data = await resp.json()
            body = data.get("body")
            return body.strip() if body else None
        except Exception as err:  # noqa: BLE001 - network errors of any kind are non-fatal here
            if attempt == 0:
                _LOGGER.debug(
                    "GitHub release fetch error for %s, retrying once: %s", url, err
                )
                await asyncio.sleep(2)
                continue
            _LOGGER.debug("GitHub release fetch error for %s: %s", url, err)
            return None
    return None


async def _fetch_addon_changelog(hass: HomeAssistant, slug: str) -> str | None:
    """Fetch a Supervisor add-on's changelog text.

    Add-on update entities have no release_url and are not GitHub-hosted
    releases - their changelog instead comes from Supervisor itself, at the
    same "/addons/{slug}/changelog" endpoint the HA frontend calls. There is
    no public/stable API for this from a custom integration, so this reuses
    Home Assistant's own internal Supervisor connection (the `hassio`
    integration's handler). This reaches into `hassio` internals that are
    not a documented custom-integration API and could break on a future HA
    update - if that happens, this simply returns None and the caller falls
    back to the generic "update available" message, exactly as if no
    changelog had been found at all.
    """
    try:
        from homeassistant.components.hassio.const import (  # noqa: PLC0415
            DATA_COMPONENT,
        )

        supervisor = hass.data[DATA_COMPONENT]
        changelog = await supervisor.send_command(
            f"/addons/{slug}/changelog", method="get", return_text=True
        )
    except Exception as err:  # noqa: BLE001 - any failure here is non-fatal
        _LOGGER.debug("Add-on changelog fetch failed for %s: %s", slug, err)
        return None
    return changelog.strip() if changelog else None


TAG_RE = re.compile(r"<script[^>]*>.*?</script>|<style[^>]*>.*?</style>|<[^>]+>", re.DOTALL)
WHITESPACE_RE = re.compile(r"[ \t]+")
BLANK_LINES_RE = re.compile(r"\n{3,}")


async def _fetch_html_page_text(hass: HomeAssistant, url: str) -> str | None:
    """Fetch a web page and strip it down to plain-ish text.

    Crude tag-stripping only (no real HTML parser is bundled) - this leaves
    some navigation/footer text mixed in with the real content, which is why
    the translation prompt is told to ignore anything that isn't actual
    release notes rather than assuming the input is already clean.
    """
    session = async_get_clientsession(hass)
    try:
        async with session.get(url, timeout=15) as resp:
            if resp.status != 200:
                _LOGGER.debug("Release notes page fetch failed (%s) for %s", resp.status, url)
                return None
            html = await resp.text()
    except Exception as err:  # noqa: BLE001
        _LOGGER.debug("Release notes page fetch error for %s: %s", url, err)
        return None

    text = TAG_RE.sub("\n", html)
    text = WHITESPACE_RE.sub(" ", text)
    text = BLANK_LINES_RE.sub("\n\n", text)
    text = text.strip()
    return text or None


async def _translate_changelog(
    hass: HomeAssistant,
    options: dict[str, Any],
    title: str,
    changelog_text: str,
    lang: str,
    *,
    noisy_source: bool = False,
    version_line: str | None = None,
) -> str | None:
    """Ask the configured AI Task entity to translate/summarize the changelog.

    Target language defaults to Home Assistant's own interface language
    (`hass.config.language`) unless overridden in the config entry.

    noisy_source=True is used for text scraped from an HTML page (rather
    than a clean GitHub/Supervisor API body) - it both allows a larger input
    budget (the real content can sit well past the nav/footer boilerplate)
    and tells the model explicitly to ignore anything that isn't actual
    release notes.

    When options["alert_mode_only"] is set, the AI is instead asked to
    classify the release as breaking or not (structured output) and this
    returns None when it judges there are no breaking changes - the caller
    treats None as "nothing to notify about".
    """
    ai_task_entity = options.get("ai_task_entity")
    max_chars = MAX_HTML_CHANGELOG_CHARS if noisy_source else MAX_CHANGELOG_CHARS
    language_label = LANGUAGE_NAMES.get(lang, f"ISO 639-1 code '{lang}'")
    noise_hint = (
        " The provided text was scraped from a raw web page and likely contains "
        "navigation menus, footer text, or other unrelated content: ignore anything "
        "that isn't actually the release notes for this version."
        if noisy_source
        else ""
    )

    if options.get("alert_mode_only"):
        instructions = (
            f"Review the following release notes for the Home Assistant "
            f"integration '{title}' and decide whether this release contains "
            "breaking changes for a typical user: renamed or removed "
            "entities/services, required configuration migrations, or any "
            "other change that could break an existing automation or "
            "dashboard. Purely internal changes (refactoring, CI, typos, "
            "new optional features, bug fixes that don't change existing "
            "behavior) are NOT breaking changes." + noise_hint + "\n\n"
            f"{changelog_text[:max_chars]}"
        )
        structure = {
            "has_breaking_changes": {
                "description": "True only if this release contains breaking changes as defined above.",
                "required": True,
                "selector": {"boolean": {}},
            },
            "summary": {
                "description": (
                    f"If has_breaking_changes is true, a translation/summary in "
                    f"{language_label} (3 to 5 sentences) of the breaking changes "
                    "only. Empty string otherwise."
                ),
                "required": True,
                "selector": {"text": {}},
            },
        }
        try:
            result = await hass.services.async_call(
                "ai_task",
                "generate_data",
                {
                    "task_name": "changelog breaking-change check",
                    "instructions": instructions,
                    "entity_id": ai_task_entity,
                    "structure": structure,
                },
                blocking=True,
                return_response=True,
            )
            data = result.get("data") if isinstance(result, dict) else None
            if not isinstance(data, dict) or not data.get("has_breaking_changes"):
                return None
            summary = data.get("summary")
            # has_breaking_changes is True here, so a falsy summary means
            # the AI confirmed a breaking change but failed to produce the
            # actual text - use "translation_failed" wording, not
            # "no_changelog" (release notes were found and were breaking,
            # the AI just didn't return a usable summary for them).
            return (
                str(summary).strip()
                if summary
                else _fallback(lang, "translation_failed", title=title)
            )
        except Exception as err:  # noqa: BLE001
            _LOGGER.warning(
                "AI Task breaking-change check failed for %s: %s - skipping "
                "notification (alert mode only notifies on confirmed "
                "breaking changes, so a failed/unknown classification must "
                "not produce one either)",
                title, err,
            )
            return _AI_CLASSIFICATION_UNKNOWN

    instructions = (
        f"Review the following release notes for the Home Assistant "
        f"integration '{title}' and categorize the changes, in "
        f"{language_label}, into three short bullet lists: new features or "
        "additions, bug fixes, and breaking changes (renamed or removed "
        "entities/services/options, required configuration migrations, or "
        "anything that could break an existing automation or dashboard). "
        "Ignore purely internal technical details (refactoring, CI, code "
        "typos) - only list changes that matter to an end user. Keep each "
        "bullet to one short sentence." + noise_hint + "\n\n"
        f"{changelog_text[:max_chars]}"
    )
    structure = {
        "new_features": {
            "description": (
                f"Bullet list in {language_label} of new features or "
                "additions in this release. Empty list if none."
            ),
            "required": True,
            "selector": {"text": {"multiple": True}},
        },
        "fixes": {
            "description": (
                f"Bullet list in {language_label} of bug fixes in this "
                "release. Empty list if none."
            ),
            "required": True,
            "selector": {"text": {"multiple": True}},
        },
        "breaking_changes": {
            "description": (
                f"Bullet list in {language_label} of breaking changes in "
                "this release, as defined above. Empty list if none."
            ),
            "required": True,
            "selector": {"text": {"multiple": True}},
        },
    }
    try:
        result = None
        last_err: Exception | None = None
        for attempt in range(2):
            try:
                result = await hass.services.async_call(
                    "ai_task",
                    "generate_data",
                    {
                        "task_name": "changelog translation",
                        "instructions": instructions,
                        "entity_id": ai_task_entity,
                        "structure": structure,
                    },
                    blocking=True,
                    return_response=True,
                )
                break
            except Exception as inner_err:  # noqa: BLE001
                last_err = inner_err
                if attempt == 0:
                    # A transient AI Task failure (e.g. the model
                    # provider returning a temporary "high demand"/503
                    # error) shouldn't burn the one-shot notification
                    # opportunity for this version - retry once after a
                    # short delay before giving up.
                    await asyncio.sleep(2)
        if result is None and last_err is not None:
            raise last_err
        data = result.get("data") if isinstance(result, dict) else None
        if not isinstance(data, dict):
            # The AI Task call succeeded but didn't return the expected
            # structured shape at all - genuinely nothing usable to show,
            # same "translation_failed" wording as an outright exception.
            return _fallback(lang, "translation_failed", title=title)
        # A well-formed response with all three lists empty is a
        # legitimate result (e.g. a release that's purely internal
        # refactoring/CI with nothing user-facing to report), not a
        # failure - it still renders as a categorized message, just with
        # every section showing the "none" placeholder.
        return _format_categorized_message(
            lang,
            data.get("new_features") or [],
            data.get("fixes") or [],
            data.get("breaking_changes") or [],
            version_line=version_line,
        )
    except Exception as err:  # noqa: BLE001
        _LOGGER.warning("AI Task translation failed for %s: %s", title, err)
        return _fallback(lang, "translation_failed", title=title)


async def _deliver(
    hass: HomeAssistant,
    options: dict[str, Any],
    entity_id: str,
    title: str,
    message: str,
    lang: str,
) -> bool:
    """Deliver the translated summary via the configured notification channels.

    Returns True if at least one enabled channel succeeded, False otherwise
    (or if no channel was enabled at all).
    """
    delivered = False
    notif_title = _fallback(lang, "notif_title", title=title)

    if options.get("use_persistent_notification", True):
        try:
            await hass.services.async_call(
                "persistent_notification",
                "create",
                {
                    "title": notif_title,
                    "message": message,
                    "notification_id": f"{DOMAIN}_{entity_id}",
                },
            )
            delivered = True
            _LOGGER.debug("persistent_notification.create succeeded for %s", title)
        except Exception as err:  # noqa: BLE001
            _LOGGER.warning("persistent_notification.create failed: %s", err)

    if options.get("use_mobile_notification", True):
        notify_target = options.get("notify_service")
        # The config flow's entity selector has multiple=True, so this is
        # normally a list (one or more notify.* entities, e.g. phone + tablet)
        # - but tolerate a bare string too (single entity picked, or an
        # older entry from before multi-device support was added).
        if isinstance(notify_target, str):
            notify_target = [notify_target]
        if not notify_target:
            _LOGGER.warning(
                "use_mobile_notification is on but no notify_service is configured "
                "for %s - skipping mobile notification.", title,
            )
        else:
            # notify_target entries are notify.* ENTITY ids picked via the
            # config flow's entity selector (e.g. "notify.iphone_fred") -
            # modern HA notify entities are not callable as their own
            # dynamic service (there is no such thing as a
            # "notify.iphone_fred" service). They must be addressed
            # through the generic notify.send_message service with an
            # explicit target - passing all of them at once sends to every
            # configured device in a single call.
            try:
                await hass.services.async_call(
                    "notify",
                    "send_message",
                    {"title": notif_title, "message": message},
                    target={"entity_id": notify_target},
                )
                delivered = True
                _LOGGER.debug("Notification via %s succeeded for %s", notify_target, title)
            except Exception as err:  # noqa: BLE001
                _LOGGER.warning("Notification via %s failed: %s", notify_target, err)

    return delivered
