name: Liste des donateurs BuyMeACoffee

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write

jobs:
  bmac-readme:
    name: Update Buy Me A Coffee section in this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: akosbalasko/coffee-readme@021a2db498f0682fe902eca059c04cc800825c0a # v1.0.4
        with:
          BUY_ME_A_COFFEE_TOKEN: ${{ secrets.BMC_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER_OF_MESSAGES: 5
